#!/bin/bash 

ES_NUC=$1
ES_EL=$2
ES_EX=$3
ES_MUF=$4
ES_POL=$5
ATNUM=$6
EV_IE=$7
EV_HA=$(bc -l <<< ${EV_IE}/27.2114)
ELS=$8
if [ ${ES_EL} -eq 4 ]
then
    if [ ! -f z_$(printf "%03d" ${ATNUM}).den ]
    then
        #cp $(which elsepa | sed 's/elsepa$//')z_$(printf "%03d" ${ATNUM}).den .
        cp $(find $(which elsepa | sed 's/elsepa$//') -name z_$(printf "%03d" ${ATNUM}).den) .
    fi
fi
if [ ${ELS} -eq 1 ]
then
echo "IZ      ${ATNUM}
MNUCL   ${ES_NUC}
MELEC   ${ES_EL}
MEXCH   ${ES_EX}
MUFFIN  ${ES_MUF}
MCPOL   ${ES_POL}
IELEC  -1
EV      ${EV_IE}" > elsepa.in
    elsepa < elsepa.in > /dev/null
    cat dcs.dat |  sed '/#/d' | sed '/^\s*$/d' | awk '{print $1*3.14159265359/180" "$4}' > elast_cs.dat
elif [ ${ELS} -eq 0 ]
then
    radial <<< "$ES_EL $ATNUM $EV_HA" > /dev/null
    cat dcs.dat |  sed '/#/d' | sed '/^\s*$/d' | awk '{print $1*3.14159265359/180" "$4}' > elast_cs.dat
fi
